import type {
  ApplicantData,
  FraudRiskAssessment,
  JobRequirementInput,
  NormalizedApplicant,
  ProofCandidateSignal,
  TalentProfile,
} from "../../shared/src/index.js";
import {
  getTalentProfileFullName,
  isTalentProfile,
  mapApplicantToTalentProfile,
} from "../../shared/src/index.js";

export interface ApplicantToolbox {
  normalizeApplicant(
    applicant: ApplicantData,
    job: JobRequirementInput,
    proofSignal?: ProofCandidateSignal,
  ): Promise<NormalizedApplicant>;
}

export class DefaultApplicantToolbox implements ApplicantToolbox {
  async normalizeApplicant(
    applicant: ApplicantData,
    job: JobRequirementInput,
    proofSignal?: ProofCandidateSignal,
  ): Promise<NormalizedApplicant> {
    const profile = isTalentProfile(applicant)
      ? applicant
      : mapApplicantToTalentProfile(applicant);
    const profileId = profile.id ?? crypto.randomUUID();
    const fullName = getTalentProfileFullName(profile) || "Unknown Candidate";
    const normalizedSkills = uniqueLowercase(profile.skills.map((skill) => skill.name));
    const yearsExperience = inferYearsExperience(profile);
    const evidence = [
      profile.headline,
      profile.bio ?? "",
      ...profile.experience.map((entry) => [
        entry.company,
        entry.role,
        entry.description,
        entry.technologies.join(", "),
      ].join(" ").trim()),
      ...profile.projects.map((project) => [
        project.name,
        project.role,
        project.description,
        project.technologies.join(", "),
      ].join(" ").trim()),
    ].filter(Boolean);
    const educationLevel = profile.education[0]?.degree;

    return {
      id: profileId,
      fullName,
      displayName: job.anonymizeCandidates ? anonymizeName(profileId) : fullName,
      source: profile.source,
      profile: {
        ...profile,
        id: profileId,
      },
      normalizedSkills,
      yearsExperience,
      educationLevel,
      location: profile.location,
      evidence: evidence.slice(0, 5),
      summary: [profile.headline, profile.bio].filter(Boolean).join(" ").slice(0, 240) ||
        "No applicant summary provided.",
      fraudRisk: assessFraudRisk(profile),
      proof: proofSignal ?? {
        status: job.proofHire?.enabled ? "not_started" : "not_required",
        score: 0,
        summary: job.proofHire?.enabled
          ? "No verified ProofHire performance has been recorded yet."
          : "ProofHire is not required for this job.",
        passed: false,
        requiredSatisfied: !job.proofHire?.enabled,
      },
    };
  }
}

function uniqueLowercase(values: string[]): string[] {
  return [...new Set(values.map((value) => value.trim().toLowerCase()).filter(Boolean))];
}

function anonymizeName(id: string): string {
  return `Candidate ${id.slice(-4).toUpperCase()}`;
}

function inferYearsExperience(profile: TalentProfile): number {
  const explicitSkillYears = profile.skills.map((skill) => skill.yearsOfExperience).filter(Number.isFinite);
  if (explicitSkillYears.length > 0) {
    return Math.max(...explicitSkillYears);
  }

  const dated = profile.experience
    .map((entry) => calculateYearSpan(entry.startDate, entry.endDate))
    .filter((value) => value > 0);

  if (dated.length > 0) {
    return Math.max(...dated);
  }

  const text = [profile.headline, profile.bio ?? ""].join(" ");
  const match = text.match(/(\d+)\+?\s+years?/i);
  return match ? Number.parseInt(match[1], 10) : 0;
}

function calculateYearSpan(startDate: string, endDate: string): number {
  if (!startDate) {
    return 0;
  }

  const start = Date.parse(`${startDate}-01`);
  const endValue = !endDate || endDate === "Present"
    ? Date.now()
    : Date.parse(`${endDate}-01`);

  if (!Number.isFinite(start) || !Number.isFinite(endValue) || endValue <= start) {
    return 0;
  }

  const years = (endValue - start) / (1000 * 60 * 60 * 24 * 365.25);
  return Math.max(0, Math.round(years));
}

function assessFraudRisk(profile: TalentProfile): FraudRiskAssessment {
  const signals: string[] = [];
  const text = [
    profile.headline,
    profile.bio ?? "",
    ...profile.experience.map((entry) => entry.description),
    ...profile.projects.map((project) => project.description),
  ]
    .join(" ")
    .toLowerCase();

  if (profile.email && /mailinator|tempmail|guerrillamail/i.test(profile.email)) {
    signals.push("Disposable email domain detected");
  }
  if (!profile.phone) {
    signals.push("Missing phone number");
  }
  if (/lorem ipsum|generated by ai|sample resume/i.test(text)) {
    signals.push("Resume contains synthetic or placeholder language");
  }
  if (text.length < 80) {
    signals.push("Very limited applicant evidence");
  }

  const level =
    signals.length >= 3 ? "high" : signals.length >= 1 ? "medium" : "low";

  return { level, signals };
}
