export class DefaultApplicantToolbox {
    async normalizeApplicant(applicant, _job) {
        const normalizedSkills = uniqueLowercase(applicant.skills ?? extractSkills(applicant));
        const yearsExperience = applicant.yearsExperience ?? inferYearsExperience(applicant);
        const evidence = [
            ...(applicant.workHistory ?? []),
            applicant.profileSummary ?? "",
            applicant.rawResumeText ?? "",
        ].filter(Boolean);
        return {
            id: applicant.id,
            fullName: applicant.fullName,
            displayName: job.anonymizeCandidates ? anonymizeName(applicant.id) : applicant.fullName,
            source: applicant.source,
            normalizedSkills,
            yearsExperience,
            educationLevel: applicant.educationLevel,
            location: applicant.location,
            evidence: evidence.slice(0, 5),
            summary: applicant.profileSummary ??
                applicant.rawResumeText?.slice(0, 240) ??
                "No applicant summary provided.",
            fraudRisk: assessFraudRisk(applicant),
        };
    }
}
function extractSkills(applicant) {
    const rawText = [
        applicant.profileSummary ?? "",
        applicant.rawResumeText ?? "",
        ...(applicant.workHistory ?? []),
    ]
        .join(" ")
        .toLowerCase();
    const knownSkills = [
        "typescript",
        "javascript",
        "react",
        "next.js",
        "node.js",
        "node",
        "mongodb",
        "python",
        "tailwind",
        "redux",
        "graphql",
        "rest",
        "docker",
        "kubernetes",
        "machine learning",
        "gemini",
        "prompt engineering",
    ];
    return knownSkills.filter((skill) => rawText.includes(skill));
}
function inferYearsExperience(applicant) {
    const text = [applicant.rawResumeText ?? "", applicant.profileSummary ?? ""].join(" ");
    const match = text.match(/(\d+)\+?\s+years?/i);
    return match ? Number.parseInt(match[1], 10) : 0;
}
function uniqueLowercase(values) {
    return [...new Set(values.map((value) => value.trim().toLowerCase()).filter(Boolean))];
}
function anonymizeName(id) {
    return `Candidate ${id.slice(-4).toUpperCase()}`;
}
function assessFraudRisk(applicant) {
    const signals = [];
    const text = [applicant.rawResumeText ?? "", applicant.profileSummary ?? ""].join(" ").toLowerCase();
    if (applicant.email && /mailinator|tempmail|guerrillamail/i.test(applicant.email)) {
        signals.push("Disposable email domain detected");
    }
    if (!applicant.phone) {
        signals.push("Missing phone number");
    }
    if (/lorem ipsum|generated by ai|sample resume/i.test(text)) {
        signals.push("Resume contains synthetic or placeholder language");
    }
    if (text.length < 80) {
        signals.push("Very limited applicant evidence");
    }
    const level = signals.length >= 3 ? "high" : signals.length >= 1 ? "medium" : "low";
    return { level, signals };
}
