import cookieParser from "cookie-parser";
import cors from "cors";
import express from "express";
import helmet from "helmet";
import type { ApplicantData, JobRequirementInput } from "../../packages/shared/src/index.js";
import { API_PORT, getAllowedOrigins, validateRuntimeConfig } from "./config.js";
import { initRepos } from "./repos.js";
import { attachUser } from "./middleware/auth.js";
import { csrfOriginCheck } from "./middleware/csrf.js";
import { initSecurityStore } from "./security/store.js";
import { apiLimiter } from "./middleware/rateLimit.js";
import { DEFAULT_PROOF_CHALLENGE_TEMPLATES } from "./repositories.js";
import { createRunRecord } from "./helpers.js";
import { authRouter } from "./routes/auth.js";
import { jobsRouter } from "./routes/jobs.js";
import { applicationsRouter } from "./routes/applications.js";
import { proofhireRouter } from "./routes/proofhire.js";
import { interviewsRouter } from "./routes/interviews.js";
import { notificationsRouter } from "./routes/notifications.js";
import { profilesRouter } from "./routes/profiles.js";
import { screeningRouter } from "./routes/screening.js";
import { mentorRouter, miscRouter, recruiterRouter, systemRouter, trainingRouter } from "./routes/training.js";

export const bootTime = new Date();

const demoApplicants: ApplicantData[] = [
  {
    id: "app-1", fullName: "Aline Mukamana", source: "umurava_profile",
    skills: ["TypeScript", "Next.js", "Node.js", "MongoDB", "Prompt Engineering"],
    yearsExperience: 4, educationLevel: "Bachelor", location: "Kigali",
    phone: "+250700000001", email: "aline@example.com",
    profileSummary: "Built recruiter tools and internal dashboards for talent operations teams.",
  },
  {
    id: "app-2", fullName: "Jean Claude Nshimiyimana", source: "resume_upload",
    skills: ["React", "JavaScript", "Node.js", "REST"], yearsExperience: 2,
    educationLevel: "Bachelor", location: "Kigali", email: "candidate@mailinator.com",
    rawResumeText: "Frontend-heavy engineer with 2 years experience building HR forms and admin dashboards. Sample resume generated by AI.",
  },
  {
    id: "app-3", fullName: "Diane Uwase", source: "spreadsheet_row",
    skills: ["TypeScript", "Redux", "Next.js", "MongoDB", "Gemini", "Prompt Engineering"],
    yearsExperience: 5, educationLevel: "Bachelor", location: "Kigali",
    phone: "+250700000003", email: "diane@example.com",
    profileSummary: "Worked on AI-assisted operations products with structured candidate scoring.",
  },
];

const demoJob: JobRequirementInput = {
  title: "AI HR Product Engineer",
  summary: "Build recruiter-facing workflows for screening and shortlisting job applicants.",
  requiredSkills: ["TypeScript", "Next.js", "Node.js", "MongoDB"],
  preferredSkills: ["Redux", "Prompt Engineering", "Gemini"],
  minimumYearsExperience: 3, educationLevel: "Bachelor", location: "Kigali",
  dealbreakers: ["no mongodb", "visa sponsorship required"], anonymizeCandidates: true,
  screeningWeights: { skills: 35, experience: 20, education: 10, relevance: 15, proof: 20 },
  proofHire: { enabled: true, mode: "required", challengeId: DEFAULT_PROOF_CHALLENGE_TEMPLATES[0]?.id, proofWeight: 20 },
};

export function createApp() {
  const app = express();
  app.disable("x-powered-by");
  app.set("trust proxy", 1);

  // Secure headers (CSP off — API is JSON-only; HSTS/frameguard/nosniff on).
  app.use(helmet({ contentSecurityPolicy: false, crossOriginEmbedderPolicy: false }));
  app.use(cors({
    origin: (origin, cb) => {
      if (!origin) return cb(null, true); // curl / server-to-server
      if (getAllowedOrigins().includes(origin)) return cb(null, true);
      return cb(new Error("CORS: origin not allowed"));
    },
    // Browsers reach the API same-origin through the app's /api proxy; CORS only matters
    // for direct calls, which get credentials only from allow-listed origins.
    credentials: true,
    allowedHeaders: ["Content-Type"],
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    maxAge: 600,
  }));
  // JSON body with sane cap (resume base64 goes through this — 15MB ceiling
  // matches the Zod schema; rejects oversized payloads with 413).
  app.use(express.json({ limit: "15mb" }));
  app.use(cookieParser());
  app.use(csrfOriginCheck);
  app.use(attachUser);
  app.use(apiLimiter);

  app.get("/health", (_req, res) => { res.status(200).json({ ok: true }); });
  app.get("/api/demo", async (_req, res) => {
    res.status(200).json(await createRunRecord({ job: demoJob, applicants: demoApplicants, shortlistSize: 3 }));
  });

  app.use("/api/auth", authRouter);
  app.use("/api/jobs", jobsRouter);
  app.use("/api/applications", applicationsRouter);
  app.use("/api/proofhire", proofhireRouter);
  app.use("/api/interviews", interviewsRouter);
  app.use("/api/notifications", notificationsRouter);
  app.use("/api/profiles", profilesRouter);
  app.use("/api", screeningRouter); // /screen, /screenings, /reviews, /ingest/*
  app.use("/api/training", trainingRouter);
  app.use("/api/mentor", mentorRouter);
  app.use("/api/recruiter", recruiterRouter);
  app.use("/api/system", systemRouter);
  app.use("/api", miscRouter); // /stats, /activity, /users/delete/*

  // 404 JSON (replaces node:http fallthrough) + CORS-aware error handler.
  app.use((_req, res) => { res.status(404).json({ error: "Not found" }); });
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  app.use((err: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
    if (err instanceof SyntaxError && "body" in (err as unknown as Record<string, unknown>)) {
      res.status(400).json({ error: "Invalid JSON body" });
      return;
    }
    if (err instanceof Error && err.message.startsWith("CORS")) {
      res.status(403).json({ error: "Origin not allowed" });
      return;
    }
    console.error("[api] Unhandled error:", err);
    res.status(500).json({ error: "Internal server error" });
  });

  return app;
}

export async function startServer(): Promise<void> {
  validateRuntimeConfig();
  await initRepos();
  await initSecurityStore();
  const app = createApp();
  app.listen(API_PORT, () => {
    console.log(`Umurava AI API (Express) listening on http://localhost:${API_PORT}`);
  });
}
