import "dotenv/config";
import { createServer } from "node:http";

import { ScreeningOrchestrator } from "../../packages/engine/src/index.js";
import type {
  ActivityLog,
  ApplicationStatus,
  ApplicantData,
  CreateApplicationInput,
  CreateJobInput,
  CreateProofChallengeInput,
  Interview,
  InterviewType,
  Job,
  JobRequirementInput,
  Notification,
  ProofChallenge,
  ProofHireConfig,
  ProofSubmission,
  RecruiterReviewInput,
  RankedCandidate,
  ScreeningRequest,
  ScreeningRunRecord,
  SystemHealth,
  SystemStats,
  TalentProfile,
  User,
  UserRole,
} from "../../packages/shared/src/index.js";
import { isTalentProfile } from "../../packages/shared/src/index.js";

import {
  ApplicationRepository,
  JobRepository,
  ProfileRepository,
  ProofChallengeRepository,
  ProofSubmissionRepository,
  ScreeningRepository,
  InterviewRepository,
  NotificationRepository,
  ActivityLogRepository,
  UserRepository,
  createRepository,
  createUserRepository,
  createJobRepository,
  createApplicationRepository,
  createProfileRepository,
  createProofChallengeRepository,
  createProofSubmissionRepository,
  createInterviewRepository,
  createNotificationRepository,
  createActivityLogRepository,
  buildActivityLog,
  buildApplication,
  buildDefaultJob,
  buildInterview,
  buildNotification,
  buildProofChallenge,
  buildProofSignal,
  buildProofSubmission,
  buildReviewRecord,
  toPublicUser,
  DEFAULT_PROOF_CHALLENGE_TEMPLATES,
} from "./repositories.js";
import { getUserFromRequest, hashPassword, verifyPassword } from "./auth.js";
import { parseApplicantsCsv } from "./csv.js";
import { deriveProofApplicantStatus, evaluateProofSubmission } from "./proofhire.js";
import { parseResumeUpload } from "./resume.js";
import type { TrainingRecommendation } from "../../packages/shared/src/index.js";
import {
  buildMentorResponse,
  buildSkillGapRecommendations,
  getOrCreateMentorSession,
  getTrainingModuleById,
  getTrainingProgress,
  guessSkillFromMessage,
  listTrainingModules,
  markTrainingUnitComplete,
  normalizeRecommendationReason,
  persistSession,
  respond,
} from "./training.js";

const orchestrator = new ScreeningOrchestrator();
const port = Number.parseInt(process.env.API_PORT ?? "4000", 10);

let screeningRepo: ScreeningRepository;
let userRepo: UserRepository;
let jobRepo: JobRepository;
let applicationRepo: ApplicationRepository;
let profileRepo: ProfileRepository;
let proofChallengeRepo: ProofChallengeRepository;
let proofSubmissionRepo: ProofSubmissionRepository;
let interviewRepo: InterviewRepository;
let notificationRepo: NotificationRepository;
let activityLogRepo: ActivityLogRepository;

let serverStartTime = new Date();

const demoApplicants: ApplicantData[] = [
  {
    id: "app-1",
    fullName: "Aline Mukamana",
    source: "umurava_profile",
    skills: ["TypeScript", "Next.js", "Node.js", "MongoDB", "Prompt Engineering"],
    yearsExperience: 4,
    educationLevel: "Bachelor",
    location: "Kigali",
    phone: "+250700000001",
    email: "aline@example.com",
    profileSummary: "Built recruiter tools and internal dashboards for talent operations teams.",
  },
  {
    id: "app-2",
    fullName: "Jean Claude Nshimiyimana",
    source: "resume_upload",
    skills: ["React", "JavaScript", "Node.js", "REST"],
    yearsExperience: 2,
    educationLevel: "Bachelor",
    location: "Kigali",
    email: "candidate@mailinator.com",
    rawResumeText: "Frontend-heavy engineer with 2 years experience building HR forms and admin dashboards. Sample resume generated by AI.",
  },
  {
    id: "app-3",
    fullName: "Diane Uwase",
    source: "spreadsheet_row",
    skills: ["TypeScript", "Redux", "Next.js", "MongoDB", "Gemini", "Prompt Engineering"],
    yearsExperience: 5,
    educationLevel: "Bachelor",
    location: "Kigali",
    phone: "+250700000003",
    email: "diane@example.com",
    profileSummary: "Worked on AI-assisted operations products with structured candidate scoring.",
  },
  {
    id: "app-4",
    source: "umurava_profile",
    firstName: "Kevin",
    lastName: "Iradukunda",
    email: "kevin@example.com",
    headline: "Backend engineer focused on hiring workflows and AI-assisted screening.",
    bio: "Builds recruiter tooling with structured profile evaluation and explainable ranking.",
    location: "Kigali",
    skills: [
      { name: "Node.js", level: "Advanced", yearsOfExperience: 5 },
      { name: "TypeScript", level: "Advanced", yearsOfExperience: 5 },
      { name: "MongoDB", level: "Intermediate", yearsOfExperience: 3 },
    ],
    experience: [
      {
        company: "Umurava",
        role: "Backend Engineer",
        startDate: "2022-01",
        endDate: "Present",
        description: "Built APIs and screening pipelines for recruiter workflows.",
        technologies: ["Node.js", "MongoDB", "TypeScript"],
        isCurrent: true,
      },
    ],
    education: [
      {
        institution: "AUCA",
        degree: "Bachelor",
        fieldOfStudy: "Computer Science",
        startYear: 2018,
        endYear: 2022,
      },
    ],
    projects: [
      {
        name: "Hiring Insights Dashboard",
        description: "Structured scoring dashboard for recruiter review.",
        technologies: ["Next.js", "Node.js"],
        role: "Backend Engineer",
        startDate: "2023-02",
        endDate: "2023-10",
      },
    ],
    availability: {
      status: "Open to Opportunities",
      type: "Full-time",
    },
    socialLinks: {
      linkedin: "https://linkedin.com/in/kevin-iradukunda",
      github: "https://github.com/kevin-iradukunda",
    },
  },
];

const demoJob: JobRequirementInput = {
  title: "AI HR Product Engineer",
  summary: "Build recruiter-facing workflows for screening and shortlisting job applicants.",
  requiredSkills: ["TypeScript", "Next.js", "Node.js", "MongoDB"],
  preferredSkills: ["Redux", "Prompt Engineering", "Gemini"],
  minimumYearsExperience: 3,
  educationLevel: "Bachelor",
  location: "Kigali",
  dealbreakers: ["no mongodb", "visa sponsorship required"],
  anonymizeCandidates: true,
  screeningWeights: {
    skills: 35,
    experience: 20,
    education: 10,
    relevance: 15,
    proof: 20,
  },
  proofHire: {
    enabled: true,
    mode: "required",
    challengeId: DEFAULT_PROOF_CHALLENGE_TEMPLATES[0]?.id,
    proofWeight: 20,
  },
};

function buildStarterProfile(user: { firstName: string; lastName: string; email: string }): TalentProfile {
  return {
    firstName: user.firstName,
    lastName: user.lastName,
    email: user.email,
    headline: "",
    location: "",
    skills: [],
    experience: [],
    education: [],
    projects: [],
    availability: {
      status: "Open to Opportunities",
      type: "Full-time",
    },
    source: "umurava_profile",
  };
}

const server = createServer(async (request, response) => {
  response.setHeader("Access-Control-Allow-Origin", "*");
  response.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
  response.setHeader("Access-Control-Allow-Methods", "GET,POST,PUT,DELETE,OPTIONS");

  if (request.method === "OPTIONS") {
    response.writeHead(204);
    response.end();
    return;
  }

  const url = request.url ?? "";
  const pathname = url.split("?")[0] ?? "";
  const parts = pathname.split("/").filter(Boolean);

  if (request.url === "/health" && request.method === "GET") {
    writeJson(response, 200, { ok: true });
    return;
  }

  // Platform stats endpoint
  if (request.url === "/api/stats" && request.method === "GET") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "recruiter") {
      writeJson(response, 403, { error: "Only recruiters can access stats" });
      return;
    }

    try {
      const jobs = await jobRepo.findByRecruiter(user.id);
      const jobIds = jobs.map(j => j.id);
      const applications = await applicationRepo.findByJobs(jobIds);
      const allJobs = await jobRepo.findPublished();

      // Fetch screening runs for metrics
      let avgMatch = 0;
      let screenedCount = 0;
      let totalScore = 0;
      let scoredCandidates = 0;

      try {
        const runs = await screeningRepo.listRuns();
        for (const run of runs) {
          if (run.result?.shortlisted) {
            for (const candidate of run.result.shortlisted) {
              if (candidate.score?.total !== undefined) {
                totalScore += candidate.score.total;
                scoredCandidates++;
              }
            }
            screenedCount += run.result.totalApplicants || 0;
          }
        }
        avgMatch = scoredCandidates > 0 ? Math.round(totalScore / scoredCandidates) : 0;
      } catch (screeningError) {
        console.error("Failed to fetch screening metrics:", screeningError);
      }

      const timeSavedMinutes = screenedCount * 15;
      const timeSavedHours = Math.floor(timeSavedMinutes / 60);

      const stats = {
        totalApplicants: applications.length,
        acceptedApplicants: applications.filter(a => a.status === "accepted").length,
        totalJobs: allJobs.length,
        publishedJobs: allJobs.filter(j => j.status === "published").length,
        closedJobs: allJobs.filter(j => j.status === "closed").length,
        systemUptime: Math.floor((Date.now() - serverStartTime.getTime()) / 1000),
        avgMatch,
        screenedCount,
        timeSavedHours,
      };

      writeJson(response, 200, stats);
      return;
    } catch (error) {
      writeJson(response, 500, { error: "Failed to fetch stats" });
      return;
    }
  }

  // System health endpoint
  if (request.url === "/api/system/health" && request.method === "GET") {
    const health: SystemHealth = {
      api: "connected",
      database: "connected",
      lastBackup: new Date().toISOString(),
    };

    writeJson(response, 200, health);
    return;
  }

  // Activity log endpoint
  if (request.url === "/api/activity" && request.method === "GET") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "recruiter") {
      writeJson(response, 403, { error: "Only recruiters can access activity logs" });
      return;
    }

    try {
      const activities = await activityLogRepo.findByRecruiter(user.id, 50);
      writeJson(response, 200, { activities });
      return;
    } catch (error) {
      writeJson(response, 500, { error: "Failed to fetch activity logs" });
      return;
    }
  }

  if (request.url === "/api/demo" && request.method === "GET") {
    const run = await createRunRecord({
      job: demoJob,
      applicants: demoApplicants,
      shortlistSize: 3,
    });
    writeJson(response, 200, run);
    return;
  }

  if (request.url === "/api/screen" && request.method === "POST") {
    try {
      const body = await readJsonBody<ScreeningRequest>(request);
      const run = await createRunRecord(body);
      writeJson(response, 200, run);
      return;
    } catch (error) {
      writeJson(response, 400, {
        error: error instanceof Error ? error.message : "Invalid request body",
      });
      return;
    }
  }

  if (request.url === "/api/screenings" && request.method === "GET") {
    writeJson(response, 200, await screeningRepo.listRuns());
    return;
  }

  if (pathname.startsWith("/api/screenings/") && parts.length === 3) {
    const id = parts[2];
    const run = await screeningRepo.getRun(id);
    if (!run) {
      writeJson(response, 404, { error: "Screening run not found" });
      return;
    }
    writeJson(response, 200, {
      run,
      reviews: await screeningRepo.listReviews(id),
    });
    return;
  }

  if (request.url === "/api/reviews" && request.method === "POST") {
    try {
      const body = await readJsonBody<RecruiterReviewInput>(request);
      const review = buildReviewRecord(body);
      await screeningRepo.saveReview(review);
      writeJson(response, 201, review);
      return;
    } catch (error) {
      writeJson(response, 400, {
        error: error instanceof Error ? error.message : "Invalid review body",
      });
      return;
    }
  }

  if (request.url === "/api/ingest/csv" && request.method === "POST") {
    try {
      const body = await readJsonBody<{ csvText: string }>(request);
      writeJson(response, 200, { applicants: parseApplicantsCsv(body.csvText) });
      return;
    } catch (error) {
      writeJson(response, 400, {
        error: error instanceof Error ? error.message : "Invalid CSV body",
      });
      return;
    }
  }

  if (request.url === "/api/ingest/resume" && request.method === "POST") {
    try {
      const body = await readJsonBody<{ mimeType: string; base64: string }>(request);
      const profile = await parseResumeUpload(body);
      
      const applicant = {
        id: profile.id || `applicant-${crypto.randomUUID()}`,
        fullName: `${profile.firstName} ${profile.lastName}`.trim() || "Unknown",
        source: "resume_upload" as const,
        skills: profile.skills?.map((s) => s.name) || [],
        yearsExperience: profile.experience?.length ? Math.max(...profile.experience.map((e) => {
          const start = parseInt(e.startDate?.slice(0, 4) || "0");
          const end = e.endDate?.toLowerCase() === "present" || !e.endDate 
            ? new Date().getFullYear() 
            : parseInt(e.endDate?.slice(0, 4) || "0");
          return end - start;
        })) : undefined,
        educationLevel: profile.education?.[0]?.degree,
        location: profile.location,
        rawResumeText: undefined,
        profileSummary: profile.bio?.slice(0, 240),
        email: profile.email,
        phone: profile.phone,
      };
      
      writeJson(response, 200, { applicant });
      return;
    } catch (error) {
      writeJson(response, 400, {
        error: error instanceof Error ? error.message : "Invalid resume body",
      });
      return;
    }
  }

  if (request.url === "/api/auth/register" && request.method === "POST") {
    try {
      const body = await readJsonBody<{ username: string; firstName: string; lastName: string; email: string; password: string; role: UserRole }>(request);

      if (!body.username || !body.firstName || !body.lastName || !body.email || !body.password || !body.role) {
        writeJson(response, 400, { error: "Username, firstName, lastName, email, password, and role are required" });
        return;
      }

      if (body.username.length < 3 || body.username.length > 20) {
        writeJson(response, 400, { error: "Username must be 3-20 characters" });
        return;
      }

      if (!/^[a-zA-Z0-9_]+$/.test(body.username)) {
        writeJson(response, 400, { error: "Username can only contain letters, numbers, and underscores" });
        return;
      }

      if (!["applicant", "recruiter"].includes(body.role)) {
        writeJson(response, 400, { error: "Role must be 'applicant' or 'recruiter'" });
        return;
      }

      if (body.password.length < 6) {
        writeJson(response, 400, { error: "Password must be at least 6 characters" });
        return;
      }

      const existingUsername = await userRepo.findByUsername(body.username);
      if (existingUsername) {
        writeJson(response, 409, { error: "Username already taken" });
        return;
      }

      const existingEmail = await userRepo.findByEmail(body.email);
      if (existingEmail) {
        writeJson(response, 409, { error: "Email already registered" });
        return;
      }

      const now = new Date().toISOString();
      const user: User = {
        id: crypto.randomUUID(),
        username: body.username,
        firstName: body.firstName,
        lastName: body.lastName,
        email: body.email,
        passwordHash: await hashPassword(body.password),
        role: body.role,
        createdAt: now,
        updatedAt: now,
      };

      await userRepo.create(user);

      const { generateToken } = await import("./auth.js");
      const token = await generateToken(user);

      writeJson(response, 201, { user: toPublicUser(user), token });
      return;
    } catch (error) {
      writeJson(response, 500, {
        error: error instanceof Error ? error.message : "Registration failed",
      });
      return;
    }
  }

  if (request.url === "/api/auth/login" && request.method === "POST") {
    try {
      const body = await readJsonBody<{ emailOrUsername: string; password: string }>(request);

      if (!body.emailOrUsername || !body.password) {
        writeJson(response, 400, { error: "Email/Username and password are required" });
        return;
      }

      const user = await userRepo.findByEmailOrUsername(body.emailOrUsername);
      if (!user) {
        writeJson(response, 401, { error: "Invalid email/username or password" });
        return;
      }

      const isValid = await verifyPassword(body.password, user.passwordHash);
      if (!isValid) {
        writeJson(response, 401, { error: "Invalid email/username or password" });
        return;
      }

      const { generateToken } = await import("./auth.js");
      const token = await generateToken(user);

      writeJson(response, 200, { user: toPublicUser(user), token });
      return;
    } catch (error) {
      writeJson(response, 500, {
        error: error instanceof Error ? error.message : "Login failed",
      });
      return;
    }
  }

  if (request.url === "/api/auth/delete" && request.method === "DELETE") {
    try {
      const user = await getUserFromRequest(request);
      if (!user) {
        writeJson(response, 401, { error: "Unauthorized" });
        return;
      }

      await userRepo.delete(user.id);
      writeJson(response, 200, { message: "Account deleted successfully" });
      return;
    } catch (error) {
      writeJson(response, 500, {
        error: error instanceof Error ? error.message : "Delete failed",
      });
      return;
    }
  }

  if (request.url?.startsWith("/api/users/delete/") && request.method === "DELETE") {
    try {
      const currentUser = await getUserFromRequest(request);
      if (!currentUser) {
        writeJson(response, 401, { error: "Unauthorized" });
        return;
      }

      const usernameToDelete = request.url.split("/api/users/delete/")[1];
      if (!usernameToDelete) {
        writeJson(response, 400, { error: "Username required" });
        return;
      }

      const decodedUsername = decodeURIComponent(usernameToDelete);
      if (currentUser.username.toLowerCase() !== decodedUsername.toLowerCase()) {
        writeJson(response, 403, { error: "You can only delete your own account" });
        return;
      }

      const userToDelete = await userRepo.findByUsername(decodedUsername);
      if (!userToDelete) {
        writeJson(response, 404, { error: "User not found" });
        return;
      }

      await userRepo.delete(userToDelete.id);
      writeJson(response, 200, { message: `User ${usernameToDelete} deleted successfully` });
      return;
    } catch (error) {
      writeJson(response, 500, {
        error: error instanceof Error ? error.message : "Delete failed",
      });
      return;
    }
  }

  if (request.url === "/api/auth/me" && request.method === "GET") {
    const user = await getUserFromRequest(request);
    if (!user) {
      writeJson(response, 401, { error: "Unauthorized" });
      return;
    }
    writeJson(response, 200, { user });
    return;
  }

  if (request.url === "/api/proofhire/templates" && request.method === "GET") {
    writeJson(response, 200, { templates: DEFAULT_PROOF_CHALLENGE_TEMPLATES });
    return;
  }

  if (request.url === "/api/proofhire/challenges" && request.method === "GET") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "recruiter") {
      writeJson(response, 403, { error: "Only recruiters can access ProofHire challenges" });
      return;
    }

    const challenges = await proofChallengeRepo.listByRecruiter(user.id);
    writeJson(response, 200, { challenges });
    return;
  }

  if (request.url === "/api/proofhire/challenges" && request.method === "POST") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "recruiter") {
      writeJson(response, 403, { error: "Only recruiters can create ProofHire challenges" });
      return;
    }

    try {
      const body = await readJsonBody<CreateProofChallengeInput>(request);
      if (!body.title || !body.instructions || !body.prompt || !body.testCases?.length) {
        writeJson(response, 400, { error: "Title, instructions, prompt, and test cases are required" });
        return;
      }

      const challenge = buildProofChallenge(body, user.id);
      await proofChallengeRepo.create(challenge);
      writeJson(response, 201, { challenge });
      return;
    } catch (error) {
      writeJson(response, 400, {
        error: error instanceof Error ? error.message : "Invalid ProofHire challenge body",
      });
      return;
    }
  }

  if (request.url === "/api/proofhire/my-submissions" && request.method === "GET") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "applicant") {
      writeJson(response, 403, { error: "Only applicants can access their submissions" });
      return;
    }

    const submissions = await proofSubmissionRepo.listByApplicant(user.id);
    const enrichedSubmissions = await Promise.all(
      submissions.map(async (sub) => {
        const challenge = await proofChallengeRepo.findById(sub.challengeId);
        const job = await jobRepo.findById(sub.jobId);
        return {
          ...sub,
          challengeTitle: challenge?.title || "Unknown Challenge",
          jobTitle: job?.title || "Unknown Job",
          challengeInstructions: challenge?.instructions || "",
          challengePrompt: challenge?.prompt || "",
        };
      }),
    );

    writeJson(response, 200, { submissions: enrichedSubmissions });
    return;
  }

  if (parts[0] === "api" && parts[1] === "proofhire" && parts[2] === "challenges" && parts.length === 4) {
    const challengeId = parts[3];
    const challenge = await proofChallengeRepo.findById(challengeId);
    if (!challenge) {
      writeJson(response, 404, { error: "Challenge not found" });
      return;
    }

    if (request.method === "GET") {
      writeJson(response, 200, { challenge });
      return;
    }

    const user = await getUserFromRequest(request);
    if (!user || user.role !== "recruiter" || challenge.recruiterId !== user.id) {
      writeJson(response, 403, { error: "Only the owning recruiter can update this challenge" });
      return;
    }

    if (request.method === "PUT") {
      const body = await readJsonBody<Partial<ProofChallenge>>(request);
      await proofChallengeRepo.update(challengeId, body);
      writeJson(response, 200, { challenge: await proofChallengeRepo.findById(challengeId) });
      return;
    }
  }

  if (parts[0] === "api" && parts[1] === "proofhire" && parts[2] === "jobs" && parts.length === 5 && parts[4] === "config" && request.method === "PUT") {
    const jobId = parts[3];
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "recruiter") {
      writeJson(response, 403, { error: "Only recruiters can configure ProofHire for a job" });
      return;
    }

    const job = await ownsJob(user.id, jobId);
    if (!job) {
      writeJson(response, 404, { error: "Job not found" });
      return;
    }

    const body = await readJsonBody<{ proofHire: ProofHireConfig }>(request);
    const config = normalizeProofHireConfig(body.proofHire);
    if (config.enabled && config.challengeId) {
      const challenge = await proofChallengeRepo.findById(config.challengeId);
      if (!challenge || challenge.recruiterId !== user.id) {
        writeJson(response, 400, { error: "Challenge must exist and belong to the recruiter" });
        return;
      }
    }

    await jobRepo.update(jobId, { proofHire: config });
    writeJson(response, 200, { job: await jobRepo.findById(jobId) });
    return;
  }

  if (parts[0] === "api" && parts[1] === "proofhire" && parts[2] === "jobs" && parts.length === 5 && parts[4] === "challenge" && request.method === "GET") {
    const jobId = parts[3];
    const job = await jobRepo.findById(jobId);
    if (!job || !job.proofHire.enabled || !job.proofHire.challengeId) {
      writeJson(response, 404, { error: "ProofHire challenge not configured for this job" });
      return;
    }

    const challenge = await proofChallengeRepo.findById(job.proofHire.challengeId);
    if (!challenge) {
      writeJson(response, 404, { error: "Challenge not found" });
      return;
    }

    writeJson(response, 200, { challenge, mode: job.proofHire.mode });
    return;
  }

  if (parts[0] === "api" && parts[1] === "proofhire" && parts[2] === "jobs" && parts.length === 5 && parts[4] === "questions" && request.method === "GET") {
    const jobId = parts[3];
    const job = await jobRepo.findById(jobId);
    if (!job) {
      writeJson(response, 404, { error: "Job not found" });
      return;
    }

    const submissions = await proofSubmissionRepo.listByJob(jobId);
    const questions = submissions.map((sub) => ({
      challengeId: sub.challengeId,
      title: "",
      type: "",
      hintCount: 0,
      referenceCount: 0,
      submissionCount: 1,
    }));

    writeJson(response, 200, { questions });
    return;
  }

  if (parts[0] === "api" && parts[1] === "proofhire" && parts[2] === "jobs" && parts.length === 5 && parts[4] === "results" && request.method === "GET") {
    const jobId = parts[3];
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "recruiter") {
      writeJson(response, 403, { error: "Only recruiters can view ProofHire results" });
      return;
    }

    const job = await ownsJob(user.id, jobId);
    if (!job) {
      writeJson(response, 404, { error: "Job not found" });
      return;
    }

    const submissions = await proofSubmissionRepo.listByJob(jobId);
    writeJson(response, 200, { submissions, proofHire: job.proofHire });
    return;
  }

  if (parts[0] === "api" && parts[1] === "proofhire" && parts[2] === "jobs" && parts.length === 5 && parts[4] === "submission" && request.method === "GET") {
    const jobId = parts[3];
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "applicant") {
      writeJson(response, 403, { error: "Only applicants can access ProofHire submissions" });
      return;
    }

    const submission = await proofSubmissionRepo.findByJobAndApplicant(jobId, user.id);
    writeJson(response, 200, { submission });
    return;
  }

  if (parts[0] === "api" && parts[1] === "proofhire" && parts[2] === "jobs" && parts.length === 5 && parts[4] === "submission" && request.method === "POST") {
    const jobId = parts[3];
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "applicant") {
      writeJson(response, 403, { error: "Only applicants can create ProofHire submissions" });
      return;
    }

    const job = await jobRepo.findById(jobId);
    if (!job || !job.proofHire.enabled || !job.proofHire.challengeId) {
      writeJson(response, 404, { error: "ProofHire challenge not configured for this job" });
      return;
    }

    const challenge = await proofChallengeRepo.findById(job.proofHire.challengeId);
    if (!challenge) {
      writeJson(response, 404, { error: "Challenge not found" });
      return;
    }

    const body = await readJsonBody<{ code: string; language?: string }>(request);
    const existing = await proofSubmissionRepo.findByJobAndApplicant(jobId, user.id);

    if (existing) {
      await proofSubmissionRepo.update(existing.id, {
        code: body.code,
        language: body.language ?? existing.language,
        status: "draft",
      });
      writeJson(response, 200, { submission: await proofSubmissionRepo.findById(existing.id), challenge });
      return;
    }

    const submission = buildProofSubmission(jobId, challenge.id, user.id, body.code, body.language ?? "typescript");
    await proofSubmissionRepo.create(submission);
    writeJson(response, 201, { submission, challenge });
    return;
  }

  if (parts[0] === "api" && parts[1] === "proofhire" && parts[2] === "jobs" && parts.length === 6 && parts[4] === "submission" && parts[5] === "evaluate" && request.method === "POST") {
    const jobId = parts[3];
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "applicant") {
      writeJson(response, 403, { error: "Only applicants can submit ProofHire solutions" });
      return;
    }

    const job = await jobRepo.findById(jobId);
    if (!job || !job.proofHire.enabled || !job.proofHire.challengeId) {
      writeJson(response, 404, { error: "ProofHire challenge not configured for this job" });
      return;
    }

    const challenge = await proofChallengeRepo.findById(job.proofHire.challengeId);
    const submission = await proofSubmissionRepo.findByJobAndApplicant(jobId, user.id);
    if (!challenge || !submission) {
      writeJson(response, 404, { error: "Submission or challenge not found" });
      return;
    }

    const evaluation = evaluateProofSubmission(challenge, submission.code);
    const submittedAt = new Date().toISOString();
    await proofSubmissionRepo.update(submission.id, {
      status: "evaluated",
      evaluation,
      submittedAt,
    });

    const updatedSubmission = await proofSubmissionRepo.findById(submission.id);
    const proofStatus = deriveProofApplicantStatus(updatedSubmission, job.proofHire.mode === "required");
    const existingApplication = await applicationRepo.findByJobAndApplicant(jobId, user.id);
    if (existingApplication) {
      await applicationRepo.update(existingApplication.id, {
        proofHireStatus: proofStatus,
        proofSubmissionId: updatedSubmission?.id,
        proofScore: evaluation.score,
        proofCompletedAt: submittedAt,
      });
    }

    writeJson(response, 200, { submission: updatedSubmission, evaluation, proofStatus });
    return;
  }

  if (request.url === "/api/jobs" && request.method === "GET") {
    const jobs = await jobRepo.findPublished();
    const jobsWithCounts = await Promise.all(jobs.map(async (job) => {
      const applications = await applicationRepo.findByJob(job.id);
      return { ...job, candidateCount: applications.length };
    }));
    writeJson(response, 200, { jobs: jobsWithCounts });
    return;
  }

  if (request.url === "/api/jobs" && request.method === "POST") {
    const user = await getUserFromRequest(request);
    if (!user) {
      writeJson(response, 401, { error: "Unauthorized" });
      return;
    }
    if (user.role !== "recruiter") {
      writeJson(response, 403, { error: "Only recruiters can create jobs" });
      return;
    }

    try {
      const body = await readJsonBody<CreateJobInput>(request);
      if (!body.title || !body.summary || !body.requiredSkills?.length) {
        writeJson(response, 400, { error: "Title, summary, and required skills are required" });
        return;
      }

      if (body.proofHire?.enabled && body.proofHire.challengeId) {
        const challenge = await proofChallengeRepo.findById(body.proofHire.challengeId);
        if (!challenge || challenge.recruiterId !== user.id) {
          writeJson(response, 400, { error: "ProofHire challenge must belong to the recruiter" });
          return;
        }
      }

      const job = buildDefaultJob(body, user.id);
      await jobRepo.create(job);
      await activityLogRepo.create(buildActivityLog({
        recruiterId: user.id,
        event: "job_created",
        jobId: job.id,
        jobTitle: job.title,
      }));
      writeJson(response, 201, { job });
      return;
    } catch (error) {
      writeJson(response, 400, {
        error: error instanceof Error ? error.message : "Invalid request body",
      });
      return;
    }
  }

  if (parts[0] === "api" && parts[1] === "jobs" && parts.length === 3) {
    const jobId = parts[2];

    if (request.method === "GET") {
      const job = await jobRepo.findById(jobId);
      if (!job) {
        writeJson(response, 404, { error: "Job not found" });
        return;
      }
      writeJson(response, 200, { job });
      return;
    }

    const user = await getUserFromRequest(request);
    if (!user) {
      writeJson(response, 401, { error: "Unauthorized" });
      return;
    }

    if (request.method === "PUT") {
      if (user.role !== "recruiter") {
        writeJson(response, 403, { error: "Only recruiters can update jobs" });
        return;
      }

      const job = await ownsJob(user.id, jobId);
      if (!job) {
        writeJson(response, 404, { error: "Job not found" });
        return;
      }

      try {
        const body = await readJsonBody<Partial<Job>>(request);
        if (body.proofHire?.enabled && body.proofHire.challengeId) {
          const challenge = await proofChallengeRepo.findById(body.proofHire.challengeId);
          if (!challenge || challenge.recruiterId !== user.id) {
            writeJson(response, 400, { error: "ProofHire challenge must belong to the recruiter" });
            return;
          }
        }
        await jobRepo.update(jobId, body);
        const updatedJob = await jobRepo.findById(jobId);
        writeJson(response, 200, { job: updatedJob });
        return;
      } catch (error) {
        writeJson(response, 400, {
          error: error instanceof Error ? error.message : "Invalid request body",
        });
        return;
      }
    }

    if (request.method === "DELETE") {
      if (user.role !== "recruiter") {
        writeJson(response, 403, { error: "Only recruiters can delete jobs" });
        return;
      }

      const job = await ownsJob(user.id, jobId);
      if (!job) {
        writeJson(response, 404, { error: "Job not found" });
        return;
      }

      await jobRepo.delete(jobId);
      writeJson(response, 204, {});
      return;
    }
  }

  if (parts[0] === "api" && parts[1] === "jobs" && parts.length === 4 && parts[3] === "publish") {
    const jobId = parts[2];
    const user = await getUserFromRequest(request);

    if (!user || user.role !== "recruiter") {
      writeJson(response, 403, { error: "Only recruiters can publish jobs" });
      return;
    }

    const job = await ownsJob(user.id, jobId);
    if (!job) {
      writeJson(response, 404, { error: "Job not found" });
      return;
    }

    const wasPublished = job.status === "published";
    await jobRepo.updateStatus(jobId, "published");
    const publishedJob = await jobRepo.findById(jobId);

    if (publishedJob && !wasPublished) {
      await notifyApplicantsAboutPublishedJob(publishedJob);
    }

    writeJson(response, 200, { job: publishedJob });
    return;
  }

  if (parts[0] === "api" && parts[1] === "jobs" && parts.length === 4 && parts[3] === "close") {
    const jobId = parts[2];
    const user = await getUserFromRequest(request);

    if (!user || user.role !== "recruiter") {
      writeJson(response, 403, { error: "Only recruiters can close jobs" });
      return;
    }

    const job = await ownsJob(user.id, jobId);
    if (!job) {
      writeJson(response, 404, { error: "Job not found" });
      return;
    }

    await jobRepo.updateStatus(jobId, "closed");
    await activityLogRepo.create(buildActivityLog({
      recruiterId: user.id,
      event: "job_closed",
      jobId: job.id,
      jobTitle: job.title,
    }));
    writeJson(response, 200, { job: await jobRepo.findById(jobId) });
    return;
  }

  if (parts[0] === "api" && parts[1] === "jobs" && parts.length === 4 && parts[3] === "applications") {
    const jobId = parts[2];
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "recruiter") {
      writeJson(response, 403, { error: "Only recruiters can view applicants for a job" });
      return;
    }

    const job = await ownsJob(user.id, jobId);
    if (!job) {
      writeJson(response, 404, { error: "Job not found" });
      return;
    }

    const applications = await applicationRepo.findByJob(jobId);
    console.log("[GET_APPLICATIONS] Found:", applications.length, "for job:", jobId);
    for (const app of applications) {
      console.log("[GET_APPLICATIONS] App:", app.id, "screeningResult:", !!app.screeningResult);
    }
    writeJson(response, 200, { applications });
    return;
  }

  if (request.url === "/api/recruiter/jobs" && request.method === "GET") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "recruiter") {
      writeJson(response, 403, { error: "Only recruiters can access this" });
      return;
    }

    const jobs = await jobRepo.findByRecruiter(user.id);
    writeJson(response, 200, { jobs });
    return;
  }

  if (request.url === "/api/recruiter/activity" && request.method === "GET") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "recruiter") {
      writeJson(response, 403, { error: "Only recruiters can access this" });
      return;
    }

    const jobs = await jobRepo.findByRecruiter(user.id);
    const jobIds = jobs.map(j => j.id);
    
    const activities: Array<{
      type: "new_application" | "status_change";
      timestamp: string;
      candidateName: string;
      jobTitle: string;
      newStatus: string;
      previousStatus: string | null;
    }> = [];

    for (const jobId of jobIds) {
      const applications = await applicationRepo.findByJob(jobId);
      
      for (const app of applications) {
        // New application
        activities.push({
          type: "new_application",
          timestamp: app.createdAt,
          candidateName: app.profile?.firstName && app.profile?.lastName 
            ? `${app.profile.firstName} ${app.profile.lastName}`
            : app.applicantId,
          jobTitle: jobs.find(j => j.id === jobId)?.title || "Unknown Job",
          newStatus: app.status,
          previousStatus: null,
        });

        // Status change if updatedAt differs from createdAt
        if (app.updatedAt && app.createdAt && app.updatedAt !== app.createdAt) {
          activities.push({
            type: "status_change",
            timestamp: app.updatedAt,
            candidateName: app.profile?.firstName && app.profile?.lastName 
              ? `${app.profile.firstName} ${app.profile.lastName}`
              : app.applicantId,
            jobTitle: jobs.find(j => j.id === jobId)?.title || "Unknown Job",
            newStatus: app.status,
            previousStatus: "submitted", // We track current status change
          });
        }
      }
    }

    // Sort by most recent and take top 20
    activities.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
    const limited = activities.slice(0, 20);

    writeJson(response, 200, { activities: limited });
    return;
  }

  if (request.url === "/api/recruiter/notifications" && request.method === "GET") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "recruiter") {
      writeJson(response, 403, { error: "Only recruiters can access this" });
      return;
    }

    const jobs = await jobRepo.findByRecruiter(user.id);
    const jobIds = jobs.map(j => j.id);
    
    const notifications: Array<{
      id: string;
      jobTitle: string;
      candidateName: string;
      createdAt: string;
    }> = [];

    for (const jobId of jobIds) {
      const applications = await applicationRepo.findByJob(jobId);
      
      for (const app of applications) {
        // Only include unread notifications (new applications where isRead is not true)
        if (!app.isRead) {
          notifications.push({
            id: app.id,
            jobTitle: jobs.find(j => j.id === jobId)?.title || "Unknown Job",
            candidateName: app.profile?.firstName && app.profile?.lastName 
              ? `${app.profile.firstName} ${app.profile.lastName}`
              : "Unknown Candidate",
            createdAt: app.createdAt,
          });
        }
      }
    }

    // Sort by most recent and mark as read by updating applications
    notifications.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
    
    // Mark all as read
    for (const notif of notifications) {
      await applicationRepo.update(notif.id, { isRead: true });
    }

    writeJson(response, 200, { notifications, unreadCount: notifications.length });
    return;
  }

  if (request.url === "/api/applications" && request.method === "GET") {
    const user = await getUserFromRequest(request);
    if (!user) {
      writeJson(response, 401, { error: "Unauthorized" });
      return;
    }

    const applications = await applicationRepo.findByApplicant(user.id);
    writeJson(response, 200, { applications });
    return;
  }

  if (request.url === "/api/applications" && request.method === "POST") {
    const user = await getUserFromRequest(request);
    if (!user) {
      writeJson(response, 401, { error: "Unauthorized" });
      return;
    }
    if (user.role !== "applicant") {
      writeJson(response, 403, { error: "Only applicants can apply to jobs" });
      return;
    }

    try {
      const body = await readJsonBody<CreateApplicationInput>(request);

      if (!body.jobId || !body.profile) {
        writeJson(response, 400, { error: "Job ID and profile are required" });
        return;
      }

      const job = await jobRepo.findById(body.jobId);
      if (!job) {
        writeJson(response, 404, { error: "Job not found" });
        return;
      }
      if (job.status !== "published") {
        writeJson(response, 400, { error: "Job is not accepting applications" });
        return;
      }

      const proofSubmission = await proofSubmissionRepo.findByJobAndApplicant(body.jobId, user.id);
      const proofStatus = deriveProofApplicantStatus(proofSubmission, job.proofHire.enabled && job.proofHire.mode === "required");

      if (job.proofHire.enabled && job.proofHire.mode === "required" && proofStatus !== "passed") {
        writeJson(response, 400, { error: "ProofHire challenge must be passed before applying to this job" });
        return;
      }

      const existing = await applicationRepo.findByJobAndApplicant(body.jobId, user.id);
      if (existing) {
        writeJson(response, 409, { error: "You have already applied to this job" });
        return;
      }

      const application = buildApplication(body, user.id);
      application.proofHireStatus = proofStatus;
      application.proofSubmissionId = proofSubmission?.id;
      application.proofScore = proofSubmission?.evaluation?.score;
      application.proofCompletedAt = proofSubmission?.evaluation?.generatedAt;
      await applicationRepo.create(application);

      await activityLogRepo.create(buildActivityLog({
        recruiterId: job.recruiterId,
        event: "application_submitted",
        jobId: job.id,
        jobTitle: job.title,
        candidateName: `${body.profile.firstName} ${body.profile.lastName}`.trim() || user.username,
        metadata: { applicationId: application.id },
      }));

      writeJson(response, 201, { application });
      return;
    } catch (error) {
      writeJson(response, 400, {
        error: error instanceof Error ? error.message : "Invalid request body",
      });
      return;
    }
  }

  if (parts[0] === "api" && parts[1] === "applications" && parts.length === 3 && request.method === "PUT") {
    const applicationId = parts[2];
    const user = await getUserFromRequest(request);

    if (!user) {
      writeJson(response, 401, { error: "Unauthorized" });
      return;
    }

    try {
      const body = await readJsonBody<{ status: ApplicationStatus }>(request);

      if (!["submitted", "under_review", "shortlisted", "rejected", "accepted"].includes(body.status)) {
        writeJson(response, 400, { error: "Invalid status" });
        return;
      }

      const application = await applicationRepo.findById(applicationId);
      if (!application) {
        writeJson(response, 404, { error: "Application not found" });
        return;
      }

      if (user.role !== "recruiter") {
        writeJson(response, 403, { error: "Only recruiters can update application status" });
        return;
      }

      const job = await ownsJob(user.id, application.jobId);
      if (!job) {
        writeJson(response, 403, { error: "You do not own the job for this application" });
        return;
      }

      await applicationRepo.updateStatus(applicationId, body.status);
      const updated = await applicationRepo.findById(applicationId);

      if (updated && ["accepted", "rejected"].includes(body.status)) {
        await notificationRepo.create(
          buildNotification({
            userId: updated.applicantId,
            type: "status_update",
            title: body.status === "accepted" ? "Application Accepted" : "Application Rejected",
            message:
              body.status === "accepted"
                ? `Your application for ${job.title} was accepted.`
                : `Your application for ${job.title} was rejected.`,
            data: { applicationId: updated.id, jobId: updated.jobId, status: body.status },
          }),
        );
      }

      writeJson(response, 200, { application: updated });
      return;
    } catch (error) {
      writeJson(response, 400, {
        error: error instanceof Error ? error.message : "Invalid request body",
      });
      return;
    }
  }

  if (parts[0] === "api" && parts[1] === "jobs" && parts.length === 4 && parts[3] === "screen") {
    const jobId = parts[2];
    const user = await getUserFromRequest(request);

    console.log("[SCREEN] Starting screening for job:", jobId);

    if (!user || user.role !== "recruiter") {
      console.log("[SCREEN] Error: Not authorized");
      writeJson(response, 403, { error: "Only recruiters can run screening" });
      return;
    }

    try {
      const job = await jobRepo.findById(jobId);
      console.log("[SCREEN] Job found:", job?.title);

      if (!job) {
        writeJson(response, 404, { error: "Job not found" });
        return;
      }

      if (job.recruiterId !== user.id) {
        console.log("[SCREEN] Error: Not owner");
        writeJson(response, 403, { error: "You do not own this job" });
        return;
      }

      const applications = await applicationRepo.findByJob(jobId);
      console.log("[SCREEN] Applications found:", applications.length);

      if (applications.length === 0) {
        writeJson(response, 400, { error: "No applications to screen" });
        return;
      }

      const jobInput: JobRequirementInput = {
        title: job.title,
        summary: job.summary,
        requiredSkills: job.requiredSkills,
        preferredSkills: job.preferredSkills,
        minimumYearsExperience: job.minimumYearsExperience,
        educationLevel: job.educationLevel,
        location: job.location,
        dealbreakers: job.dealbreakers,
        screeningWeights: job.screeningWeights,
        proofHire: job.proofHire,
      };

      const proofSignals = await buildProofSignalsForJob(jobId, job.proofHire);
      console.log("[SCREEN] Proof signals:", proofSignals);

      const screeningRequest: ScreeningRequest = {
        job: jobInput,
        applicants: applications.map((app) => ({
          ...app.profile,
          id: app.applicantId,
        })),
        shortlistSize: 10,
        proofSignals,
      };

      console.log("[SCREEN] Running orchestrator...");
      const run = await createRunRecord(screeningRequest);
      console.log("[SCREEN] Screening complete, shortlisted:", run.result.shortlisted?.length);

      // Always update applications with screening result, even if no one is shortlisted
      const allCandidates = run.result.shortlisted?.length > 0 
        ? run.result.shortlisted 
        : applications.map<RankedCandidate>((app, idx) => ({
            applicantId: app.applicantId,
            rank: idx + 1,
            fullName: `${app.profile?.firstName || ''} ${app.profile?.lastName || ''}`.trim(),
            score: { skills: 0, experience: 0, education: 0, relevance: 0, proof: 0, total: 0 },
            matchedSkills: [],
            missingSkills: [],
            strengths: [],
            gaps: ['No strong match found'],
            recommendation: 'Does not meet current requirements',
            source: app.profile?.source ?? "umurava_profile",
            dealbreakerHits: [],
            fraudRisk: { level: "low", signals: [] },
            proof: { status: "not_required", score: 0, passed: false, requiredSatisfied: true },
          }));

      for (const candidate of allCandidates) {
        const matchingApp = applications.find((app) => app.applicantId === candidate.applicantId);
        if (matchingApp) {
          console.log("[SCREEN] Updating application:", matchingApp.id);
          await applicationRepo.updateScreeningResult(matchingApp.id, {
            jobTitle: run.result.jobTitle,
            totalApplicants: run.result.totalApplicants,
            shortlisted: allCandidates,
            generatedAt: run.result.generatedAt,
            reasoningMode: run.result.reasoningMode,
          });
        }
      }

      console.log("[SCREEN] Done, returning result");
      writeJson(response, 200, { run });
      return;
    } catch (error) {
      console.error("[SCREEN] Error:", error);
      writeJson(response, 500, {
        error: error instanceof Error ? error.message : "Screening failed",
      });
      return;
    }
  }

  // Interview scheduling endpoint
  if (request.url === "/api/interviews" && request.method === "POST") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "recruiter") {
      writeJson(response, 403, { error: "Only recruiters can schedule interviews" });
      return;
    }

    try {
      const body = await readJsonBody<{
        applicationId: string;
        jobId: string;
        candidateId: string;
        scheduledAt: string;
        duration: number;
        type: InterviewType;
        meetingLink?: string;
        notes?: string;
      }>(request);

      if (!body.applicationId || !body.jobId || !body.candidateId || !body.scheduledAt || !body.duration || !body.type) {
        writeJson(response, 400, { error: "applicationId, jobId, candidateId, scheduledAt, duration, and type are required" });
        return;
      }

      const application = await applicationRepo.findById(body.applicationId);
      if (!application) {
        writeJson(response, 404, { error: "Application not found" });
        return;
      }

      const job = await jobRepo.findById(body.jobId);
      if (!job || job.recruiterId !== user.id) {
        writeJson(response, 403, { error: "You do not own this job" });
        return;
      }

      const interview = buildInterview({
        applicationId: body.applicationId,
        jobId: body.jobId,
        candidateId: body.candidateId,
        recruiterId: user.id,
        scheduledAt: body.scheduledAt,
        duration: body.duration,
        type: body.type,
        meetingLink: body.meetingLink,
        notes: body.notes,
      });

      await interviewRepo.create(interview);

      // Create notification for the applicant
      const notification = buildNotification({
        userId: body.candidateId,
        type: "interview_scheduled",
        title: "Interview Scheduled",
        message: `You have been invited for an interview for ${job.title}. Scheduled for ${new Date(body.scheduledAt).toLocaleString()}.`,
        data: { interviewId: interview.id, jobId: body.jobId },
      });

      await notificationRepo.create(notification);

      await activityLogRepo.create(buildActivityLog({
        recruiterId: user.id,
        event: "interview_scheduled",
        jobId: body.jobId,
        jobTitle: job.title,
        candidateName: `${application.profile?.firstName ?? ""} ${application.profile?.lastName ?? ""}`.trim() || "Unknown",
      }));

      writeJson(response, 201, { interview, notification });
      return;
    } catch (error) {
      writeJson(response, 400, {
        error: error instanceof Error ? error.message : "Failed to schedule interview",
      });
      return;
    }
  }

  // Get interviews for recruiter
  if (request.url === "/api/interviews" && request.method === "GET") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "recruiter") {
      writeJson(response, 403, { error: "Only recruiters can access interviews" });
      return;
    }

    const interviews = await interviewRepo.findByRecruiter(user.id);
    writeJson(response, 200, { interviews });
    return;
  }

  // Get notifications for user
  if (request.url === "/api/notifications" && request.method === "GET") {
    const user = await getUserFromRequest(request);
    if (!user) {
      writeJson(response, 401, { error: "Unauthorized" });
      return;
    }

    const notifications = await notificationRepo.findByUser(user.id);
    writeJson(response, 200, { notifications });
    return;
  }

  if (request.url === "/api/notifications/read-all" && request.method === "POST") {
    const user = await getUserFromRequest(request);
    if (!user) {
      writeJson(response, 401, { error: "Unauthorized" });
      return;
    }

    await notificationRepo.markAllAsRead(user.id);
    writeJson(response, 200, { success: true });
    return;
  }

  // Mark notification as read
  if (parts[0] === "api" && parts[1] === "notifications" && parts.length === 4 && parts[3] === "read" && request.method === "POST") {
    const user = await getUserFromRequest(request);
    if (!user) {
      writeJson(response, 401, { error: "Unauthorized" });
      return;
    }

    const notificationId = parts[2];
    const notification = await notificationRepo.findById(notificationId);
    if (!notification) {
      writeJson(response, 404, { error: "Notification not found" });
      return;
    }
    if (notification.userId !== user.id) {
      writeJson(response, 403, { error: "Forbidden" });
      return;
    }

    await notificationRepo.markAsRead(notificationId);
    writeJson(response, 200, { success: true });
    return;
  }

  if (request.url === "/api/profiles/parse" && request.method === "POST") {
    console.log("[server] 📥 POST /api/profiles/parse called");
    try {
      const body = await readJsonBody<{ mimeType: string; base64: string }>(request);
      console.log("[server] 📄 Parsing resume, mimeType:", body.mimeType, "base64 length:", body.base64?.length);
      const profile = await parseResumeUpload(body);
      console.log("[server] ✅ Resume parsed successfully, returning profile");
      writeJson(response, 200, { profile });
      return;
    } catch (error) {
      console.error("[server] ❌ Error parsing resume:", error);
      writeJson(response, 400, {
        error: error instanceof Error ? error.message : "Failed to parse resume",
      });
      return;
    }
  }

  if (request.url === "/api/profiles" && request.method === "GET") {
    console.log("GET /api/profiles called");
    const user = await getUserFromRequest(request);
    console.log("User from request:", user);
    if (!user) {
      writeJson(response, 401, { error: "Unauthorized" });
      return;
    }
    if (user.role !== "applicant") {
      writeJson(response, 403, { error: "Only applicants can access profiles" });
      return;
    }

    const profile = await profileRepo.findByApplicant(user.id);
    console.log("Profile found:", profile ? "yes" : "no");
    if (!profile) {
      const starterProfile = buildStarterProfile(user);
      await profileRepo.save(user.id, starterProfile);
      writeJson(response, 200, { profile: starterProfile });
      return;
    }
    writeJson(response, 200, { profile });
    return;
  }

  if (request.url === "/api/profiles" && request.method === "POST") {
    console.log("POST /api/profiles called");
    const user = await getUserFromRequest(request);
    console.log("User from request:", user);
    if (!user) {
      writeJson(response, 401, { error: "Unauthorized" });
      return;
    }
    if (user.role !== "applicant") {
      writeJson(response, 403, { error: "Only applicants can save profiles" });
      return;
    }

    try {
      const body = await readJsonBody<{ profile: TalentProfile }>(request);
      console.log("Body received:", JSON.stringify(body, null, 2));
      if (!body.profile) {
        writeJson(response, 400, { error: "Profile data is required" });
        return;
      }
      await profileRepo.save(user.id, body.profile);
      console.log("Profile saved to repo for user:", user.id);
      writeJson(response, 201, { message: "Profile saved successfully", profile: body.profile });
      return;
    } catch (error) {
      console.error("Error saving profile:", error);
      writeJson(response, 400, {
        error: error instanceof Error ? error.message : "Failed to save profile",
      });
      return;
    }
  }

  if (request.url === "/api/profiles" && request.method === "PUT") {
    const user = await getUserFromRequest(request);
    if (!user) {
      writeJson(response, 401, { error: "Unauthorized" });
      return;
    }
    if (user.role !== "applicant") {
      writeJson(response, 403, { error: "Only applicants can update profiles" });
      return;
    }

    try {
      const body = await readJsonBody<{ profile: TalentProfile }>(request);
      if (!body.profile) {
        writeJson(response, 400, { error: "Profile data is required" });
        return;
      }
      await profileRepo.save(user.id, body.profile);
      writeJson(response, 200, { message: "Profile updated successfully", profile: body.profile });
      return;
    } catch (error) {
      writeJson(response, 400, {
        error: error instanceof Error ? error.message : "Failed to update profile",
      });
      return;
    }
  }

  if (request.url === "/api/training" && request.method === "GET") {
    writeJson(response, 200, { modules: listTrainingModules() });
    return;
  }

  if (parts[0] === "api" && parts[1] === "training" && parts.length === 3 && parts[2] === "recommendations" && request.method === "GET") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "applicant") {
      writeJson(response, 403, { error: "Only applicants can view training recommendations" });
      return;
    }

    const profile = await profileRepo.findByApplicant(user.id);
    const jobs = await jobRepo.findPublished();
    const raw = buildSkillGapRecommendations({
      profileSkills: (profile?.skills ?? []).map((skill) => skill.name),
      jobs: jobs.map((job) => ({ requiredSkills: job.requiredSkills, title: job.title })),
    });

    const recommendations: Array<TrainingRecommendation & { reason: string }> = raw.map((recommendation) => ({
      ...recommendation,
      reason: normalizeRecommendationReason(recommendation),
    }));

    writeJson(response, 200, { recommendations: recommendations.slice(0, 8) });
    return;
  }

  if (parts[0] === "api" && parts[1] === "training" && parts.length === 3 && parts[2] === "progress" && request.method === "GET") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "applicant") {
      writeJson(response, 403, { error: "Only applicants can view training progress" });
      return;
    }

    const progress = await getTrainingProgress(user.id);
    writeJson(response, 200, { progress });
    return;
  }

  if (parts[0] === "api" && parts[1] === "training" && parts.length === 4 && parts[2] === "progress" && request.method === "POST") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "applicant") {
      writeJson(response, 403, { error: "Only applicants can update training progress" });
      return;
    }

    try {
      const body = await readJsonBody<{ unitId: string }>(request);
      if (!body.unitId) {
        writeJson(response, 400, { error: "unitId is required" });
        return;
      }
      const progress = await markTrainingUnitComplete(user.id, parts[3], body.unitId);
      writeJson(response, 200, { progress });
      return;
    } catch (error) {
      writeJson(response, 400, {
        error: error instanceof Error ? error.message : "Failed to update training progress",
      });
      return;
    }
  }

  if (parts[0] === "api" && parts[1] === "training" && parts.length === 3 && parts[2] === "practice" && request.method === "GET") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "applicant") {
      writeJson(response, 403, { error: "Only applicants can view practice challenges" });
      return;
    }

    const jobs = await jobRepo.findPublished();
    const challenges: import("../../packages/shared/src/index.js").PracticeChallengeLite[] = [];

    for (const job of jobs) {
      if (!job.proofHire.enabled || !job.proofHire.challengeId) {
        continue;
      }
      const challenge = await proofChallengeRepo.findById(job.proofHire.challengeId);
      if (!challenge) {
        continue;
      }
      challenges.push({
        challengeId: challenge.id,
        jobId: job.id,
        jobTitle: job.title,
        title: challenge.title,
        type: challenge.type,
        requiredSkills: challenge.requiredSkills,
      });
    }

    writeJson(response, 200, { challenges });
    return;
  }

  if (parts[0] === "api" && parts[1] === "training" && parts.length === 4 && parts[2] === "practice" && parts[3] === "evaluate" && request.method === "POST") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "applicant") {
      writeJson(response, 403, { error: "Only applicants can practice ProofHire challenges" });
      return;
    }

    try {
      const body = await readJsonBody<{ challengeId: string; code: string; language?: string }>(request);
      if (!body.challengeId || typeof body.code !== "string") {
        writeJson(response, 400, { error: "challengeId and code are required" });
        return;
      }

      const challenge = await proofChallengeRepo.findById(body.challengeId);
      if (!challenge) {
        writeJson(response, 404, { error: "Challenge not found" });
        return;
      }

      const evaluation = evaluateProofSubmission(challenge, body.code);
      writeJson(response, 200, { evaluation, practice: true });
      return;
    } catch (error) {
      writeJson(response, 400, {
        error: error instanceof Error ? error.message : "Failed to evaluate practice submission",
      });
      return;
    }
  }

  if (parts[0] === "api" && parts[1] === "training" && parts.length === 4 && parts[2] === "practice" && parts[3] !== "evaluate" && request.method === "GET") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "applicant") {
      writeJson(response, 403, { error: "Only applicants can access practice challenges" });
      return;
    }

    const challenge = await proofChallengeRepo.findById(parts[3]);
    if (!challenge) {
      writeJson(response, 404, { error: "Challenge not found" });
      return;
    }

    writeJson(response, 200, { challenge });
    return;
  }

  if (parts[0] === "api" && parts[1] === "training" && parts.length === 3 && request.method === "GET") {
    const module = getTrainingModuleById(parts[2]);
    if (!module) {
      writeJson(response, 404, { error: "Training module not found" });
      return;
    }
    writeJson(response, 200, { module });
    return;
  }

  if (request.url === "/api/mentor/chat" && request.method === "POST") {
    const user = await getUserFromRequest(request);
    if (!user || user.role !== "applicant") {
      writeJson(response, 403, { error: "Only applicants can chat with the mentor" });
      return;
    }

    try {
      const body = await readJsonBody<{ skill?: string; message: string; sessionId?: string }>(request);
      if (typeof body.message !== "string") {
        writeJson(response, 400, { error: "message is required" });
        return;
      }

      const applicantId = user.id;
      let skill = body.skill?.trim() ?? "";
      let sessionId = body.sessionId;

      if (sessionId) {
        const existing = (await getOrCreateMentorSession({ applicantId, sessionId })).session;
        if (skill && existing.skill && skill !== existing.skill) {
          sessionId = undefined;
        }
        skill = skill || existing.skill;
      }

      if (!skill) {
        skill = guessSkillFromMessage(body.message, "");
      }

      const { session } = await getOrCreateMentorSession({ applicantId, sessionId, skill });
      const result = await respond(session, body.message.trim() || "");
      persistSession(session);

      const payload = buildMentorResponse(session, result);
      writeJson(response, 200, payload);
      return;
    } catch (error) {
      writeJson(response, 400, {
        error: error instanceof Error ? error.message : "Mentor chat failed",
      });
      return;
    }
  }

  writeJson(response, 404, { error: "Not found" });
});

async function startServer() {
  console.log("Initializing repositories...");
  screeningRepo = await createRepository();
  userRepo = await createUserRepository();
  jobRepo = await createJobRepository();
  applicationRepo = await createApplicationRepository();
  profileRepo = await createProfileRepository();
  proofChallengeRepo = await createProofChallengeRepository();
  proofSubmissionRepo = await createProofSubmissionRepository();
  interviewRepo = await createInterviewRepository();
  notificationRepo = await createNotificationRepository();
  activityLogRepo = await createActivityLogRepository();
  console.log("Repositories initialized.");

  server.listen(port, () => {
    console.log(`Umurava AI API listening on http://localhost:${port}`);
  });
}

startServer().catch(console.error);

async function createRunRecord(request: ScreeningRequest): Promise<ScreeningRunRecord> {
  const normalizedRequest: ScreeningRequest = {
    ...request,
    applicants: request.applicants.map((applicant) =>
      isTalentProfile(applicant)
        ? {
            ...applicant,
            id: applicant.id ?? crypto.randomUUID(),
          }
        : applicant,
    ),
  };
  const result = await orchestrator.run(normalizedRequest);
  const run: ScreeningRunRecord = {
    id: crypto.randomUUID(),
    request: normalizedRequest,
    result,
    createdAt: new Date().toISOString(),
    status: "completed",
  };
  await screeningRepo.saveRun(run);
  return run;
}

async function ownsJob(userId: string, jobId: string): Promise<Job | null> {
  const job = await jobRepo.findById(jobId);
  if (!job || job.recruiterId !== userId) {
    return null;
  }
  return job;
}

async function notifyApplicantsAboutPublishedJob(job: Job): Promise<void> {
  const applicants = await userRepo.listByRole("applicant");

  await Promise.all(
    applicants.map((applicant) =>
      notificationRepo.create(
        buildNotification({
          userId: applicant.id,
          type: "job_published",
          title: "New Job Uploaded",
          message: `${job.title} is now open for applications.`,
          data: { jobId: job.id },
        }),
      ),
    ),
  );
}

async function buildProofSignalsForJob(
  jobId: string,
  config: ProofHireConfig,
): Promise<Record<string, ReturnType<typeof buildProofSignal>>> {
  const signals: Record<string, ReturnType<typeof buildProofSignal>> = {};
  const submissions = await proofSubmissionRepo.listByJob(jobId);

  for (const submission of submissions) {
    const required = config.enabled && config.mode === "required";
    const status = deriveProofApplicantStatus(submission, required);
    signals[submission.applicantId] = buildProofSignal(status, submission.evaluation, submission.id);
  }

  return signals;
}

function normalizeProofHireConfig(input: ProofHireConfig | undefined): ProofHireConfig {
  return {
    enabled: input?.enabled ?? false,
    mode: input?.mode ?? "optional",
    challengeId: input?.challengeId,
    proofWeight: input?.proofWeight ?? 20,
  };
}

function writeJson(
  response: import("node:http").ServerResponse,
  statusCode: number,
  payload: unknown,
): void {
  response.writeHead(statusCode, { "Content-Type": "application/json" });
  response.end(JSON.stringify(payload, null, 2));
}

async function readJsonBody<T>(
  request: import("node:http").IncomingMessage,
): Promise<T> {
  const chunks: Buffer[] = [];

  for await (const chunk of request) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
  }

  const raw = Buffer.concat(chunks).toString("utf8");
  if (!raw) {
    throw new Error("Request body is empty");
  }
  return JSON.parse(raw) as T;
}
